name: check-structure
on: [push]
jobs:
  check-project-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go to repo directory
        run: cd $GITHUB_WORKSPACE
      - name: Check README
        run: test -f README.md 
      - name: Check output files
        run: |
          test -f output/output_dev.csv
          test -f output/output_test.csv
      - name: Check report
        run: |
          test -f report.pdf